apiVersion: argoproj.io/v1alpha1     
kind: Rollout  
metadata:
  name: rollout
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: nginx
  workloadRef: 
    apiVersion: apps/v1
    kind: Deployment
    name: rollout-ref-deployment
  strategy:
    blueGreen: 
      activeService: bluegreen-active 
      previewService: bluegreen-preview
      autoPromotionEnabled: false
